2022-05-11 03:49:12,025 - INFO - 
Config:
'add_train': False
'batch_size': 501
'continue_flag': ''
'cur_time': '2022_05_11_03_49_12'
'debug_mode': False
'debug_num': 500
'do_continue_train': False
'do_figure_save': False
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0.2
'epoch': 200
'feature_columns': [1, 2, 3, 4, 5]
'figure_save_path': './figure/'
'hidden_size': 512
'input_size': 5
'label_columns': [4, 5]
'label_in_feature_index': [3, 4]
'learning_rate': 0.0001
'log_save_path': './log/2022_05_11_03_49_12_pytorch/'
'lstm_layers': 2
'model_name': 'model_pytorch.pth'
'model_postfix': {'pytorch': '.pth'
'keras': '.h5'
'tensorflow': '.ckpt'}
'model_save_path': './checkpoint/pytorch/'
'output_size': 2
'patience': 3
'predict_day': 1
'random_seed': 42
'shuffle_train_data': True
'time_step': 501
'train_data_path': './gtau0.csv'
'train_data_rate': 0.9
'use_cuda': True
'used_frame': 'pytorch'
'valid_data_rate': 0.1
2022-05-11 03:49:14,339 - INFO - Epoch 0/200
2022-05-11 03:49:15,628 - ERROR - Run Error
Traceback (most recent call last):
  File "C:/Users/Liu Siwei/Desktop/DCS/Main.py", line 254, in main
    train(config, logger, [train_X, train_Y, valid_X, valid_Y])
  File "C:\Users\Liu Siwei\Desktop\DCS\Model.py", line 72, in train
    loss.backward()                     # 将loss反向传播
  File "C:\ProgramData\Anaconda3\envs\torchtest\lib\site-packages\torch\_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\ProgramData\Anaconda3\envs\torchtest\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA out of memory. Tried to allocate 492.00 MiB (GPU 0; 8.00 GiB total capacity; 6.27 GiB already allocated; 0 bytes free; 6.37 GiB reserved in total by PyTorch)
